# Generated by Django 5.2.6 on 2025-09-16 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, unique=True, verbose_name='검색 키워드')),
                ('search_count', models.PositiveIntegerField(default=1, verbose_name='검색 횟수')),
                ('last_searched_at', models.DateTimeField(auto_now=True, verbose_name='마지막 검색 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '인기 검색어',
                'verbose_name_plural': '인기 검색어들',
                'db_table': 'home_popular_search',
                'ordering': ['-search_count', '-last_searched_at'],
                'indexes': [models.Index(fields=['-search_count'], name='home_popula_search__d59db0_idx'), models.Index(fields=['-last_searched_at'], name='home_popula_last_se_8c822f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='검색어')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='검색 일시')),
                ('results_count', models.IntegerField(default=0, verbose_name='결과 개수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '검색 기록',
                'verbose_name_plural': '검색 기록들',
                'db_table': 'home_search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='home_search_created_efaa5a_idx'), models.Index(fields=['user', '-created_at'], name='home_search_user_id_5a3f30_idx')],
            },
        ),
    ]
