# Generated by Django 5.2.6 on 2025-09-28 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_keywordscore_property_recommendationcache_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='home_search_user_id_65fbe7_idx',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='parsed_keywords',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='result_count',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='search_id',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='address',
            field=models.JSONField(default=dict, help_text='주소 정보 (JSON 형태)', verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='area_range',
            field=models.CharField(blank=True, default='', help_text='~10평, 10평대, 20평대, 30평대, 40평대, 50평대, 60평대, 70평~ 중 하나', max_length=20, verbose_name='면적대'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='building_type',
            field=models.JSONField(default=list, help_text='아파트, 오피스텔, 빌라 등 (배열 형태)', verbose_name='매물유형'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='검색 기록 생성 시간', verbose_name='생성 시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='deposit',
            field=models.JSONField(blank=True, default=None, help_text='보증금 범위 [최소값] 또는 [최소값, 최대값] (원 단위)', null=True, verbose_name='보증금'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='error_type',
            field=models.CharField(blank=True, choices=[('MISSING_ADDRESS', '주소 정보 누락'), ('MISSING_TRANSACTION_TYPE', '거래유형 정보 누락'), ('MISSING_BUILDING_TYPE', '매물유형 정보 누락'), ('API_ERROR', 'API 호출 오류'), ('JSON_PARSE_ERROR', 'JSON 파싱 오류'), ('VALIDATION_ERROR', '유효성 검사 오류')], help_text='키워드 추출 실패 시 에러 유형', max_length=50, null=True, verbose_name='에러 유형'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='is_global',
            field=models.BooleanField(default=False, help_text='True인 경우 전체 사용자에 대한 키워드 의미', verbose_name='전체 사용자용'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='monthly_rent',
            field=models.JSONField(blank=True, default=None, help_text='월세 범위 [최소값] 또는 [최소값, 최대값] (원 단위)', null=True, verbose_name='월세'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='sale_price',
            field=models.JSONField(blank=True, default=None, help_text='매매가 범위 [최소값] 또는 [최소값, 최대값] (원 단위)', null=True, verbose_name='매매가'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='score',
            field=models.PositiveIntegerField(blank=True, help_text='Redis sorted set 스코어 (추후 사용)', null=True, verbose_name='스코어'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='transaction_type',
            field=models.JSONField(default=list, help_text='매매, 전세, 월세, 단기임대 (배열 형태)', verbose_name='거래유형'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='검색 기록 마지막 수정 시간', verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query_text',
            field=models.TextField(default='', help_text='사용자가 입력한 자연어 검색 쿼리', verbose_name='원본 자연어 쿼리'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='redis_key',
            field=models.CharField(blank=True, default='', help_text='Redis 캐시 키', max_length=255, verbose_name='Redis 키'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='실제 검색이 수행된 시간', verbose_name='검색 수행 시간'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='사용자 정보 (Global이 True인 경우 null)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['error_type'], name='home_search_error_t_5e8b85_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['created_at'], name='home_search_created_bf7374_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchhistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_global', True), ('user__isnull', True)), models.Q(('is_global', False), ('user__isnull', False)), _connector='OR'), name='global_user_constraint'),
        ),
    ]
