# Generated by Django 5.2.6 on 2025-09-16 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='키워드 카테고리 (address, transaction_type, building_type 등)', max_length=50)),
                ('keyword', models.CharField(help_text='키워드 값', max_length=200)),
                ('score', models.FloatField(default=0.0, help_text='키워드 스코어')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='사용자 (None인 경우 전체 사용자 키워드)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '키워드 스코어',
                'verbose_name_plural': '키워드 스코어',
                'indexes': [models.Index(fields=['user', 'category'], name='utils_keywo_user_id_017ab9_idx'), models.Index(fields=['category', 'score'], name='utils_keywo_categor_a8ba5a_idx'), models.Index(fields=['updated_at'], name='utils_keywo_updated_9d1d02_idx')],
                'unique_together': {('user', 'category', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(help_text='Redis 캐시 키', max_length=255)),
                ('properties_data', models.JSONField(help_text='추천 매물 데이터 (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='사용자 (None인 경우 전체 사용자 추천)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '추천 캐시',
                'verbose_name_plural': '추천 캐시',
                'indexes': [models.Index(fields=['user'], name='utils_recom_user_id_2b269a_idx'), models.Index(fields=['cache_key'], name='utils_recom_cache_k_014912_idx'), models.Index(fields=['updated_at'], name='utils_recom_updated_18594f_idx')],
                'unique_together': {('user', 'cache_key')},
            },
        ),
    ]
